// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsw8W8EGDbk0GodyI06CIMdx115fVxPn8',
    appId: '1:163114823018:web:0c47a0498a95d903afc913',
    messagingSenderId: '163114823018',
    projectId: 'xero-talk',
    authDomain: 'xero-talk.firebaseapp.com',
    storageBucket: 'xero-talk.appspot.com',
    measurementId: 'G-X6QHV0BFL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM2fMOE_47nmYy0QS6w9eSfNDOqMGp8Y4',
    appId: '1:163114823018:android:b705edce38159b2cafc913',
    messagingSenderId: '163114823018',
    projectId: 'xero-talk',
    storageBucket: 'xero-talk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn_JpE3zMj7_tL5yqH8MtqOHzoNqVnoRI',
    appId: '1:163114823018:ios:9ef2762e9793944eafc913',
    messagingSenderId: '163114823018',
    projectId: 'xero-talk',
    storageBucket: 'xero-talk.appspot.com',
    iosClientId: '163114823018-rufpd5iuiglp79b8rgteb35orb238ouu.apps.googleusercontent.com',
    iosBundleId: 'com.example.xeroTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn_JpE3zMj7_tL5yqH8MtqOHzoNqVnoRI',
    appId: '1:163114823018:ios:9ef2762e9793944eafc913',
    messagingSenderId: '163114823018',
    projectId: 'xero-talk',
    storageBucket: 'xero-talk.appspot.com',
    iosClientId: '163114823018-rufpd5iuiglp79b8rgteb35orb238ouu.apps.googleusercontent.com',
    iosBundleId: 'com.example.xeroTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsw8W8EGDbk0GodyI06CIMdx115fVxPn8',
    appId: '1:163114823018:web:23702fecdddf745eafc913',
    messagingSenderId: '163114823018',
    projectId: 'xero-talk',
    authDomain: 'xero-talk.firebaseapp.com',
    storageBucket: 'xero-talk.appspot.com',
    measurementId: 'G-J2ESWDY10X',
  );
}
